'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  TrendingDown,
  TrendingUp,
  Minus,
  Sparkles,
  AlertTriangle,
  Lightbulb,
  ArrowLeft,
  Calendar,
  BarChart3,
} from 'lucide-react';
import { useCurrencyStore } from '@/lib/stores/currency-store';
import { formatCurrency } from '@/lib/currency';
import Spinner from '@/app/components/Spinner';

interface AnalysisReport {
  id: number;
  llm_provider: string;
  analysis_type: string;
  prompt_tokens: number;
  completion_tokens: number;
  recommendation: string;
  reasoning: string;
  confidence_level: string;
  risk_factors: string[];
  opportunities: string[];
  data_snapshot: {
    transactions: any[];
    holdings: any[];
    taxCalculations: any[];
    timestamp: string;
  } | null;
  created_at: string;
}

export default function AnalysisDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { currency, exchangeRate } = useCurrencyStore();
  const [report, setReport] = useState<AnalysisReport | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
  }, [params.id]);

  const fetchReport = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/llm/reports/${params.id}`);
      const data = await response.json();

      if (data.success) {
        setReport(data.data);
      }
    } catch (error) {
      console.error('Error fetching report:', error);
    } finally {
      setLoading(false);
    }
  };

  const getRecommendationIcon = (recommendation: string) => {
    switch (recommendation.toLowerCase()) {
      case 'buy':
        return <TrendingUp className="h-8 w-8 text-green-600" />;
      case 'sell':
        return <TrendingDown className="h-8 w-8 text-red-600" />;
      case 'hold':
        return <Minus className="h-8 w-8 text-blue-600" />;
      default:
        return <Sparkles className="h-8 w-8" />;
    }
  };

  const getRecommendationColor = (recommendation: string) => {
    switch (recommendation.toLowerCase()) {
      case 'buy':
        return 'text-green-600 dark:text-green-400';
      case 'sell':
        return 'text-red-600 dark:text-red-400';
      case 'hold':
        return 'text-blue-600 dark:text-blue-400';
      default:
        return 'text-gray-600 dark:text-gray-400';
    }
  };

  const getConfidenceBadge = (confidence: string) => {
    const variants = {
      high: 'default',
      medium: 'secondary',
      low: 'outline',
    } as const;

    return (
      <Badge variant={variants[confidence.toLowerCase() as keyof typeof variants] || 'outline'} className="text-sm">
        {confidence} Confidence
      </Badge>
    );
  };

  const formatCurrencyValue = (value: number) => {
    return formatCurrency(value, currency, exchangeRate);
  };

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Spinner size={32} />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <p className="text-muted-foreground mb-4">Analysis report not found</p>
          <Button onClick={() => router.push('/')}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Dashboard
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-6">
      <main className="mx-auto max-w-5xl">
        {/* Header */}
        <div className="mb-6">
          <Button variant="ghost" onClick={() => router.back()} className="mb-4">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <h1 className="text-4xl font-bold">AI Portfolio Analysis</h1>
          <p className="mt-2 text-muted-foreground">
            Generated by {report.llm_provider === 'claude' ? 'Claude' : 'Gemini'} on{' '}
            {new Date(report.created_at).toLocaleString()}
          </p>
        </div>

        {/* Recommendation Card */}
        <Card className="mb-6 shadow-lg border-2">
          <CardContent className="p-6">
            <div className="flex items-center gap-4 mb-4">
              {getRecommendationIcon(report.recommendation)}
              <div>
                <h2 className={`text-3xl font-bold capitalize ${getRecommendationColor(report.recommendation)}`}>
                  {report.recommendation}
                </h2>
                {getConfidenceBadge(report.confidence_level)}
              </div>
            </div>
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Sparkles className="h-4 w-4" />
              <span>
                Analysis Type: {report.analysis_type} | Tokens: {report.prompt_tokens + report.completion_tokens}
              </span>
            </div>
          </CardContent>
        </Card>

        {/* Reasoning */}
        <Card className="mb-6 shadow-md">
          <CardHeader>
            <CardTitle>Analysis Reasoning</CardTitle>
            <CardDescription>Detailed explanation of the recommendation</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-base leading-relaxed whitespace-pre-wrap">{report.reasoning}</p>
          </CardContent>
        </Card>

        {/* Risk Factors and Opportunities */}
        <div className="grid gap-6 md:grid-cols-2 mb-6">
          {/* Risk Factors */}
          <Card className="shadow-md">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-orange-600" />
                Risk Factors
              </CardTitle>
              <CardDescription>{report.risk_factors.length} identified risks</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {report.risk_factors.map((risk, index) => (
                  <li key={index} className="flex gap-2">
                    <span className="text-orange-600 font-bold">•</span>
                    <span className="text-sm">{risk}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Opportunities */}
          <Card className="shadow-md">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="h-5 w-5 text-yellow-600" />
                Opportunities
              </CardTitle>
              <CardDescription>{report.opportunities.length} identified opportunities</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {report.opportunities.map((opportunity, index) => (
                  <li key={index} className="flex gap-2">
                    <span className="text-green-600 font-bold">•</span>
                    <span className="text-sm">{opportunity}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Portfolio Snapshot */}
        {report.data_snapshot && (
          <Card className="mb-6 shadow-md">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="h-5 w-5" />
                Portfolio Snapshot
              </CardTitle>
              <CardDescription>
                Data used for this analysis on {new Date(report.data_snapshot.timestamp).toLocaleString()}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4 md:grid-cols-3">
                <div className="rounded-lg border p-4">
                  <div className="text-sm text-muted-foreground mb-1">Total Holdings</div>
                  <div className="text-2xl font-bold">
                    {formatCurrencyValue(
                      report.data_snapshot.holdings.reduce((sum, h) => sum + (h.current_value || 0), 0)
                    )}
                  </div>
                </div>
                <div className="rounded-lg border p-4">
                  <div className="text-sm text-muted-foreground mb-1">Holdings Count</div>
                  <div className="text-2xl font-bold">{report.data_snapshot.holdings.length}</div>
                </div>
                <div className="rounded-lg border p-4">
                  <div className="text-sm text-muted-foreground mb-1">Transactions</div>
                  <div className="text-2xl font-bold">{report.data_snapshot.transactions.length}</div>
                </div>
              </div>

              {/* Holdings Breakdown */}
              {report.data_snapshot.holdings.length > 0 && (
                <div className="mt-6">
                  <h4 className="font-semibold mb-3">Holdings Breakdown</h4>
                  <div className="space-y-2">
                    {report.data_snapshot.holdings.slice(0, 5).map((holding, index) => (
                      <div key={index} className="flex items-center justify-between p-3 rounded-lg border">
                        <div>
                          <span className="font-semibold">{holding.ticker}</span>
                          <span className="text-sm text-muted-foreground ml-2">
                            {holding.total_shares} shares
                          </span>
                        </div>
                        <div className="text-right">
                          <div className="font-semibold">{formatCurrencyValue(holding.current_value)}</div>
                          <div
                            className={`text-sm ${
                              holding.adjusted_gain_loss >= 0
                                ? 'text-green-600 dark:text-green-400'
                                : 'text-red-600 dark:text-red-400'
                            }`}
                          >
                            {holding.adjusted_gain_loss >= 0 ? '+' : ''}
                            {formatCurrencyValue(holding.adjusted_gain_loss)}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Metadata */}
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              Analysis Metadata
            </CardTitle>
          </CardHeader>
          <CardContent>
            <dl className="grid gap-3 text-sm">
              <div className="flex justify-between">
                <dt className="text-muted-foreground">AI Provider</dt>
                <dd className="font-semibold capitalize">{report.llm_provider}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Analysis Type</dt>
                <dd className="font-semibold capitalize">{report.analysis_type}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Prompt Tokens</dt>
                <dd className="font-semibold">{report.prompt_tokens.toLocaleString()}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Completion Tokens</dt>
                <dd className="font-semibold">{report.completion_tokens.toLocaleString()}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Generated At</dt>
                <dd className="font-semibold">{new Date(report.created_at).toLocaleString()}</dd>
              </div>
            </dl>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
